name: repo-sync

on:
  schedule:
  - cron: '* * * * *'

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v2
      with:
        source_repo: "mattmoor/sync-source-repo"
        source_branch: "master"
        destination_repo: "mattmoor/sync-dest-repo"
        destination_branch: "master"
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
